# Generated by Django 3.2.16 on 2022-12-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accId',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='otherName1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='otherName2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='otherName3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
